[package]
name = "boids"
version = "0.1.0"
authors = ["eisendaniel <danieleisen99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
glam = "0.20.2"
rand = "0.8.5"
